import type { LucideIcon } from "lucide-react";
import {
  Activity,
  AlarmClock,
  Apple,
  BookOpen,
  Bot,
  Brain,
  Briefcase,
  Bug,
  Car,
  CheckCircle2,
  Clock3,
  CloudRain,
  Compass,
  Cpu,
  Crown,
  Crosshair,
  Droplets,
  Flame,
  Globe,
  Leaf,
  Lightbulb,
  Lock,
  MapPin,
  Mic,
  Moon,
  Mountain,
  RotateCcw,
  Scale,
  Shield,
  ShieldAlert,
  Siren,
  Sparkles,
  Stethoscope,
  Sun,
  Target,
  Thermometer,
  TriangleAlert,
  Train,
  Trash2,
  Trophy,
  UserRound,
  Users,
  Wallet,
  type LucideProps,
} from "lucide-react";

const iconRegistry: Record<string, LucideIcon> = {
  activity: Activity,
  "alarm-clock": AlarmClock,
  apple: Apple,
  "alert-triangle": TriangleAlert,
  "book-open": BookOpen,
  bot: Bot,
  brain: Brain,
  briefcase: Briefcase,
  bug: Bug,
  car: Car,
  "check-circle": CheckCircle2,
  "clock-3": Clock3,
  "cloud-rain": CloudRain,
  compass: Compass,
  cpu: Cpu,
  crown: Crown,
  crosshair: Crosshair,
  droplets: Droplets,
  flame: Flame,
  globe: Globe,
  leaf: Leaf,
  lightbulb: Lightbulb,
  lock: Lock,
  "map-pin": MapPin,
  mic: Mic,
  moon: Moon,
  mountain: Mountain,
  "rotate-ccw": RotateCcw,
  scale: Scale,
  shield: Shield,
  "shield-alert": ShieldAlert,
  siren: Siren,
  sparkles: Sparkles,
  stethoscope: Stethoscope,
  sun: Sun,
  target: Target,
  thermometer: Thermometer,
  train: Train,
  "trash-2": Trash2,
  trophy: Trophy,
  user: UserRound,
  users: Users,
  wallet: Wallet,
};

export function resolveIcon(iconName: string): LucideIcon {
  return iconRegistry[iconName] ?? Sparkles;
}

export function renderIcon(iconName: string, props?: LucideProps) {
  const Icon = resolveIcon(iconName);
  return <Icon {...props} />;
}
